version: '3.7'
services:
  gpu1:
    image: abhimazu/gpu1:v1.0
    container_name: gpu1
    privileged: true
    network_mode: host
    devices:
      - /dev/dri
  gpu2:
    image: abhimazu/gpu2:v1.0
    container_name: gpu2
    privileged: true
    network_mode: host
    devices:
      - /dev/dri
